# Generated by Django 5.0.2 on 2025-11-18 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_auto_adjust_budgets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('add_transaction', 'Add Transaction'), ('edit_transaction', 'Edit Transaction'), ('delete_transaction', 'Delete Transaction'), ('create_budget', 'Create Budget'), ('update_budget', 'Update Budget'), ('view_dashboard', 'View Dashboard'), ('view_transactions', 'View Transactions'), ('view_budget', 'View Budget'), ('view_predictions', 'View Predictions'), ('export_data', 'Export Data'), ('import_data', 'Import Data')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data about the activity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_userac_user_id_a3e34e_idx'), models.Index(fields=['activity_type', '-created_at'], name='user_userac_activit_d55874_idx')],
            },
        ),
    ]
