# Generated by Django 5.0.2 on 2025-11-20 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler'), ('electronics', 'Electronics'), ('home_loan', 'Home Loan'), ('personal_loan', 'Personal Loan'), ('gold_loan', 'Gold Loan')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('add_transaction', 'Add Transaction'), ('edit_transaction', 'Edit Transaction'), ('delete_transaction', 'Delete Transaction'), ('create_budget', 'Create Budget'), ('update_budget', 'Update Budget'), ('view_dashboard', 'View Dashboard'), ('view_transactions', 'View Transactions'), ('view_budget', 'View Budget'), ('view_predictions', 'View Predictions'), ('view_ai_insights', 'View AI Insights'), ('export_data', 'Export Data'), ('import_data', 'Import Data')], max_length=20),
        ),
        migrations.CreateModel(
            name='AIConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ai_recommendation', models.TextField()),
                ('affordability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommended_banks', models.JSONField()),
                ('risk_assessment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.loanproduct')),
            ],
        ),
    ]
