# Generated by Django 5.0.2 on 2025-11-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_loanproduct_alter_useractivity_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialgoal',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='spendingpattern',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='spendingpattern',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='aiconsultation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='user_userac_user_id_a3e34e_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='user_userac_activit_d55874_idx',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='auto_adjust_budgets',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='activated_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='monthly_tracking_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='plan_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='selected_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconsultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('savings', 'Savings'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='item_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('savings', 'Savings'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('add_transaction', 'Add Transaction'), ('update_transaction', 'Update Transaction'), ('delete_transaction', 'Delete Transaction'), ('create_budget', 'Create Budget'), ('update_budget', 'Update Budget'), ('ai_consultation', 'AI Consultation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FinancialGoal',
        ),
        migrations.DeleteModel(
            name='SpendingPattern',
        ),
    ]
