# Generated by Django 5.2.8 on 2025-11-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_financialgoal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsultation',
            name='fallback_item_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiconsultation',
            name='selected_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.loanproduct'),
        ),
    ]
