# Generated by Django 5.2.8 on 2025-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_aiconsultation_fallback_item_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('savings', 'Savings'), ('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('savings', 'Savings'), ('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment'), ('other', 'Other')], max_length=20),
        ),
    ]
