# Generated by Django 5.2.8 on 2025-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_savedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsultation',
            name='conversation_context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
